services:
  mysql:
    image: mysql:8.0.32
    container_name: peidi-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    healthcheck:
      test: "mysql ${MYSQL_DATABASE} -u${MYSQL_USERNAME} -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 60
  djangoapi:
    image: movier/peidi-django
    build: ./djangoapi
    entrypoint: /code/entrypoint.sh
    container_name: peidi-django
    volumes:
      - ./djangoapi:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - WX_APPID=${WX_APPID}
      - WX_APPSECRET=${WX_APPSECRET}
      - DingDing_APPID=${DingDing_APPID}
      - DingDing_APPKEY=${DingDing_APPKEY}
      - DingDing_APPSECRET=${DingDing_APPSECRET}
      - ALIYUNSMS_KEY=${ALIYUNSMS_KEY}
      - ALIYUNSMS_SECRET=${ALIYUNSMS_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
